import type { NextPage } from 'next';
import Head from 'next/head';

import Navigation from '../../components/navigation/Navigation';
import Feed from '../../components/feed/Feed';
import BottomMenu from '../../components/menu/BottomMenu';

import { useUserContext } from '../../contexts';

import { discoverSectionData } from '../../public/data/discoverSectionData';

const DiscoverPage: NextPage = () => {
  const { user, setUser } = useUserContext();
  const handleClick = () => setUser(!user);

  return (
    <div className='dark:bg-black'>
      <Head>
        <title>nocolor.io | discover</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='text-black dark:text-white'>
        <Navigation />
        <Feed data={discoverSectionData} />
        <BottomMenu user={user} handleClick={handleClick} />
      </main>
    </div>
  );
};

export default DiscoverPage;
