import type { NextPage } from 'next';
import Head from 'next/head';

import Navigation from '../../components/navigation/Navigation';
import DiscoverSection from '../../components/sections/discoverSection/DiscoverSection';
import BottomMenu from '../../components/bottomMenu/BottomMenu';

import { useUserContext } from '../../contexts';

const Home: NextPage = () => {
  const { user, setUser } = useUserContext();
  const handleClick = () => setUser(!user);

  return (
    <div className='dark:bg-black'>
      <Head>
        <title>nocolor.io | discover</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${!user && 'h-screen w-screen overflow-hidden'}text-black dark:text-white`}>
        <Navigation />
        <DiscoverSection />
        <BottomMenu user={user} handleClick={handleClick} />
      </main>
    </div>
  );
};

export default Home;
