import type { NextPage } from 'next';
import Head from 'next/head';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import Navigation from '../../components/navigation/Navigation';
import FeedSection from '../../components/sections/feedSection/FeedSection';
import BottomMenu from '../../components/bottomMenu/BottomMenu';

import { useUserContext } from '../../contexts';

const Home: NextPage = () => {
  const { user, setUser } = useUserContext();
  const handleClick = () => setUser(!user);

  return (
    <div className='dark:bg-black'>
      <Head>
        <title>nocolor.io | black and white</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${!user && 'h-screen overflow-hidden'}text-black dark:text-white`}>
        <Navigation />
        <FeedSection />
        <BottomMenu user={user} handleClick={handleClick} />
      </main>
    </div>
  );
};

export default Home;
