import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import Navigation from '../../components/navigation/Navigation';
import Profile from '../../components/profile/Profile';
import Feed from '../../components/feed/Feed';
import BottomMenu from '../../components/menu/BottomMenu';

import { useUserContext } from '../../contexts';

import { feedSectionData } from '../../public/data/feedSectionData';

const accountPage: NextPage = () => {
  const { user, setUser } = useUserContext();
  const handleClick = () => setUser(!user);

  return (
    <div className='dark:bg-black'>
      <Head>
        <title>nocolor.io | discover</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='text-black dark:text-white'>
        <Navigation />
        <Profile />
        <h1 className='text-2xl text-center mb-2'>your photos</h1>
        <Feed data={feedSectionData} />
        <BottomMenu user={user} handleClick={handleClick} />
      </main>
    </div>
  );
};

export default accountPage;
