import type { NextPage } from 'next';
import Head from 'next/head';

import Navigation from '../components/navigation/Navigation';
import HeroSection from '../components/sections/heroSection/HeroSection';
import FeedSection from '../components/sections/feedSection/FeedSection';
import LoginOverlay from '../components/overlays/LoginOverlay';
import BottomMenu from '../components/bottomMenu/BottomMenu';

const Home: NextPage = () => {
  const user = false;
  return (
    <div>
      <Head>
        <title>nocolor.io | black and white</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${!user ? 'h-screen overflow-hidden ' : ''}text-black dark:text-white`}>
        <Navigation />
        {!user
          ? (
            <>
              <LoginOverlay />
              <HeroSection />
            </>
          )
          : <FeedSection />}
        <BottomMenu user={user} />
      </main>
    </div>
  );
};

export default Home;
