import type { NextPage } from 'next';
import Head from 'next/head';

import Header from '../components/header/header';
import HeroSection from '../components/sections/heroSection/HeroSection';
import LoginOverlay from '../components/overlays/LoginOverlay';
import Footer from '../components/footer/Footer';

const Home: NextPage = () => {
  const user = true;
  return (
    <div>
      <Head>
        <title>nocolor.io | black and white</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${!user ? 'h-screen overflow-hidden ' : ''}text-black dark:text-white`}>
        <Header />
        {!user && <LoginOverlay />}
        <HeroSection />
        <Footer user={user} />
      </main>
    </div>
  );
};

export default Home;
