import type { NextPage } from 'next';
import Head from 'next/head';

import Navigation from '../../components/navigation/Navigation';
import UploadSection from '../../components/sections/uploadSection/UploadSection';
import BottomMenu from '../../components/bottomMenu/BottomMenu';

import { useUserContext } from '../../contexts';
import UploadPhotoOverlay from '../../components/overlays/uploadPhotoOverlay/UploadPhotoOverlay';

const Home: NextPage = () => {
  const { user, setUser } = useUserContext();
  const handleClick = () => setUser(!user);

  return (
    <div className='dark:bg-black'>
      <Head>
        <title>nocolor.io | upload photo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='h-screen overflow-hidden text-black dark:text-white'>
        <Navigation />
        <UploadSection />
        <UploadPhotoOverlay />
        <BottomMenu user={user} handleClick={handleClick} />
      </main>
    </div>
  );
};

export default Home;
